services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      POSTGRES_DATABASE: ${DATABASE_NAME:-forum}
    volumes:
      - db_nest_clean:/var/lib/postgresql/data

volumes:
  db_nest_clean:
    driver: local
