services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      POSTGRES_DATABASE: ${DATABASE_NAME:-forum}
    volumes:
      - db_nest_clean:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_nest_clean:/bitnami/redis/data
    environment:
      - REDIS_DATABASE=${REDIS_DB:-0}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}

volumes:
  db_nest_clean:
    driver: local
  redis_nest_clean:
    driver: local
